carburant/urls.py
from django.urls import path
from carburant import views


urlpatterns = [
    path('', views.home, name='home'),
    path('cards/', views.CardListView.as_view(), name='cards'),
    path('cards/<int:pk>/<str:card_number>/', views.DetailCardView.as_view(), name='supplies_from_card'),
    path('supplies/', views.SupplyListView.as_view(), name="supplies"),
    path('vehicules/', views.vehicule_list, name="vehicles"),
    path('create-supply/', views.CreateSupplyView.as_view(), name="create_supply"),
    path('update-supply/<int:pk>', views.SupplyUpdateView.as_view(), name="update_supply"),
    path('delete-supply/<int:pk>', views.SupplyDeleteView.as_view(), name="delete_supply"),
    path('export-pdf/<int:pk>/', views.print_as_pdf, name='export_pdf'),
    path('create-vehicle/', views.CreateVehicleView.as_view(), name='new_vehicle'),
    path('create-card/', views.CreateCardView.as_view(), name='new_card'),
    path('csv/<int:pk>/', views.convert_to_csv, name='csv'),
]

paci/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carburant.urls')),
    path('search', include('search.urls', namespace='search')),
]

carburant/models.py
from django.db import models
from django.shortcuts import reverse
from datetime import datetime
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords
from django.utils import timezone as tz
from carburant.func_utils import format_registration

today = datetime.now()


class CardProvider(models.Model):
    provider_name = models.CharField(_('Fournisseur de la carte'), max_length=20, unique=True)

    def __str__(self):
        return self.provider_name

    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('Fournisseur de carte')
        verbose_name_plural = _('Fournisseurs de carte')


class Card(models.Model):
    card_name: str = models.CharField(_('Nom de la carte'), max_length=50, unique=True)
    card_number: str = models.CharField(_('No de la carte'), max_length=10, unique=True)
    initial_amount: int = models.PositiveBigIntegerField(_("Montant initial"), default=600000)
    balance: int = models.PositiveBigIntegerField(_("Solde"), null=True)
    date_save = models.DateTimeField(auto_now_add=True, editable=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.card_number

    def save(self, **kwargs):
        self.balance = self.initial_amount
        super(Card, self).save(**kwargs)

    def get_absolute_url(self, **kwargs):
        return reverse('supplies_from_card', kwargs={'pk': self.pk, 'card_number': self.card_number})

    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('Carte')
        verbose_name_plural = _('Cartes')
        unique_together = [('card_name', 'card_number'),]


class RechargeCard(models.Model):
    provider = models.ForeignKey(CardProvider, on_delete=models.CASCADE, related_name="recharges",
                                 verbose_name=_("Fournisseur"))
    card = models.ForeignKey(Card, on_delete=models.CASCADE, related_name="recharges", verbose_name=_("Carte"))
    amount: int = models.PositiveIntegerField(_("Montant initial"), editable=False, null=True, blank=True)
    recharge_period = models.DateField(_("Date de rechargement"), default=f"{ today.year }-{ today.month }-1")
    date_save = models.DateTimeField(auto_now_add=True, editable=False)
    history = HistoricalRecords()

    def __str__(self):
        return f'{ self.card }'

    def save(self, **kwargs):
        self.amount = self.card.initial_amount
        super().save(**kwargs)

    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('Recharge de carte')
        verbose_name_plural = _('Recharge de cartes')
        unique_together = ('card', 'recharge_period')
        ordering = ['-recharge_period']


class Vehicle(models.Model):
    registration: str = models.CharField(_("Immat. No"), max_length=15, unique=True)
    vin: str = models.CharField(_('No châssis'), max_length=17, null=True, blank=True)
    brand: str = models.CharField(_("Marque du véhicule"), max_length=50, null=True, blank=True)
    model: str = models.CharField(_("Modèle du véhicule"), max_length=30, null=True, blank=True)
    user: str = models.CharField(_("Utilisateur"), default="", max_length=50, null=True, blank=True)
    is_service_vehicle = models.BooleanField(_("Véhicule de service ?"), default=False)

    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('Véhicule')
        verbose_name_plural = _('Véhicules')

    def __str__(self):
        return self.registration

    def save(self, **kwargs):
        self.registration = format_registration(self.registration)
        super().save(**kwargs)


class Supply(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE, related_name='supplies', verbose_name="Carte")
    supply_number: str = models.CharField("No Approv.", max_length=15, editable=False, unique=True)
    supply_date: datetime = models.DateField(_("Date d'approv."))
    ticket: int = models.PositiveBigIntegerField(unique=True)
    volume: float = models.DecimalField(max_digits=5, decimal_places=2)
    amount: int = models.PositiveIntegerField(_("Montant"))
    vehicle: Vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE,
                                         verbose_name=_('Véhicule'), related_name="supplies")
    odometer: float = models.DecimalField(_('Km'), max_digits=12, decimal_places=2, null=True, blank=True)
    service: str = models.CharField(max_length=50)
    observation: str = models.TextField()
    signature: str = models.CharField(max_length=50)
    date_save = models.DateTimeField(auto_now_add=True, editable=False)
    # created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, default=1)
    history = HistoricalRecords()

    def __str__(self):
        return f'{ self.supply_number }'

    def save(self, **kwargs):
        identifier = self.get_timestamp_split()
        self.supply_number = f"{ identifier[:3] }-{ identifier[3:6] }-{ identifier[6:] }"
        self.card.balance -= self.amount
        super().save(**kwargs)

    def get_absolute_url(self, **kwargs):
        return reverse('supply_url', kwargs={'pk': self.pk, 'id_supply': self.supply_number})

    @staticmethod
    def get_timestamp_split():
        timestamp = datetime.timestamp(tz.now())
        tm_split = str(timestamp).split('.')[0]
        return tm_split

    def display_amount_unit(self):
        return f'{self.amount} Fcfa'

    def display_volume_unit(self):
        return f'{self.volume} L'

    class Meta:
        db_table = ''
        managed = True
        verbose_name = _('Approvisionnement')
        verbose_name_plural = _('Approvisionnements')

carburant/forms.py
from django import forms
from carburant.models import Supply, Card, Vehicle, CardProvider


class SupplyForm(forms.ModelForm):
    card = forms.ModelChoiceField(queryset=Card.objects.all())
    vehicle = forms.CharField(strip=True, max_length=12, min_length=5)

    class Meta:
        model = Supply
        fields = ('supply_date', 'card',
                  'ticket', 'volume',
                  'amount', 'service',
                  'odometer',
                  'signature', 'observation')


class VehicleForm(forms.ModelForm):
    class Meta:
        fields = ['registration', 'vin', 'brand', 'model', 'user', 'is_service_vehicle']
        model = Vehicle
        widgets = {
            "registration": forms.TextInput(attrs={
                "placeholder": "Ex: 1234 HB 01"
            }),
            "vin": forms.TextInput(attrs={
                "placeholder": "Ex: LJ11PAB61KC200145"
            }),
            "brand": forms.TextInput(attrs={
                "placeholder": "Ex: Mercedes"
            }),
            "model": forms.TextInput(attrs={
                "placeholder": "Plateau"
            }),
            "user": forms.TextInput(attrs={
                "placeholder": "Ex: Atelier"
            }),
            "is_service_vehicle": forms.CheckboxInput(attrs={
                "data-caption": "Pousser à droite si véhicule de service",
                "data-role": 'switch',
                "class": 'fg-red',
            }),
        }


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        exclude = ['balance', 'date_save']

carburant/views.py
from django.shortcuts import render, reverse, HttpResponse, get_object_or_404
from django.utils import timezone as tz
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.db.models.aggregates import Sum
from carburant.func_utils import format_registration
from carburant.forms import SupplyForm, VehicleForm, CardForm
from carburant.models import Card, Supply, RechargeCard, Vehicle, CardProvider
from weasyprint import HTML, CSS
import tempfile, csv
from django.conf import settings

today = tz.now()


def home(request):
    template = 'carburant/index.html'
    nb_card = Card.objects.count()
    nb_supply = Supply.objects.filter(
        supply_date__year=today.year,
        supply_date__month=today.month
    ).count()
    vehicles = Vehicle.objects.count()
    context = {
        'cards_count': nb_card,
        'supplies_count': nb_supply,
        'vehicles_count': vehicles,
    }
    return render(request, template, context)


def vehicule_list(request):
    vehicules = Vehicle.objects.filter(is_service_vehicle=True)
    template = "carburant/vehicles.html"
    context = {'vehicles': vehicules}
    return render(request, template, context)


class SupplyListView(ListView):
    template_name = 'carburant/supplies.html'
    model = Supply
    context_object_name = 'supplies'

    def get_queryset(self):
        queryset = Supply.objects.filter(
            supply_date__year=today.year,
            supply_date__month=today.month
        )
        return queryset.order_by('-supply_date')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SupplyListView, self).get_context_data(**kwargs)
        context['today'] = today
        return context


class CardListView(ListView):
    template_name = 'carburant/cards.html'
    model = Card
    context_object_name = 'cards'

    def get_queryset(self):
        return Card.objects.order_by('-date_save')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # self.
        return context


class DetailCardView(DetailView):
    template_name = 'carburant/supplies.html'
    model = Card
    context_object_name = 'card'

    def get_context_data(self, **kwargs):
        context = super(DetailCardView, self).get_context_data(**kwargs)
        card_item_recharged_period = RechargeCard.objects.filter(
            recharge_period__month=today.month,
            recharge_period__year=today.year
        ).get(
            card=self.object,
        )
        card_selected = Card.objects.get(card_number=card_item_recharged_period)
        total_amount = Supply.objects.filter(
            card=card_selected,
            supply_date__year=today.year,
            supply_date__month=today.month,
        ).aggregate(amount_expensed=Sum('amount'))

        # Détermination du solde de la carte
        try:
            balance = self.object.initial_amount - total_amount.get('amount_expensed', 0)
        except TypeError:
            balance = self.object.initial_amount
            total_amount = 0
        context['consumption'] = total_amount
        context['balance'] = balance

        #----------------------------------------------#
        # Mise à jour de la valeur du solde dans la BDD
        Card.objects.filter(card_number=self.object).update(balance=balance)
        #----------------------------------------------#
        return context


#*********************************************************************
#   FORM CREATOR    #
class CreateSupplyView(CreateView):
    model = Supply
    form_class = SupplyForm
    template_name = 'carburant/form.html'
    success_url = reverse_lazy('supplies')

    def form_valid(self, form):
        registration = form.cleaned_data.get('vehicle')
        vehicle, created = Vehicle.objects.get_or_create(registration=format_registration(registration))
        form.instance.vehicle = vehicle
        return super(CreateSupplyView, self).form_valid(form)

    def form_invalid(self, form):
        # obj, created = Vehicle.objects.get_or_create(registration=vehicle)
        # print("VEH =>", obj.id, created)
        print(form.errors)

    def get_context_data(self, **kwargs):
        context = super(CreateSupplyView, self).get_context_data(**kwargs)
        return context


class CreateVehicleView(CreateView):
    form_class = VehicleForm
    model = Vehicle
    template_name = 'carburant/vehicle_form.html'
    success_url = reverse_lazy('home')


class CreateCardView(CreateView):
    form_class = CardForm
    model = Card
    template_name = 'carburant/card_form.html'
    success_url = reverse_lazy('cards')


class SupplyUpdateView(UpdateView):
    model = Supply
    # form_class = SupplyForm
    template_name = 'carburant/form.html'
    fields = ['vehicle', 'card', 'ticket', 'volume', 'amount', 'service',
              'observation', 'signature', 'supply_date', 'odometer']
    # slug_url_kwarg = "pk"
    # slug_field = 'id'

    def get_success_url(self):
        return reverse_lazy('supplies')

    def form_valid(self, form):
        registration = form.cleaned_data.get('vehicle')
        vehicle, created = Vehicle.objects.get_or_create(registration=registration)
        form.instance.vehicle = vehicle
        return super().form_valid(form)

    # def get_queryset(self, form):
    #     queryset = Supply.objects.get(pk=form.instance.pk)
    #     vehicle = Vehicle.objects.get(registration__)
        # return Supply.objects.get(pk=form.instance.pk)


class SupplyDeleteView(DeleteView):
    model = Supply

    def get_success_url(self):
        return reverse_lazy('supplies')


def get_data(pk=None):
    card = get_object_or_404(Card, pk=pk)
    supplies_for_card = Supply.objects.filter(
        card=card,
        supply_date__month=today.month,
        supply_date__year=today.year,
    )
    consumption_card = Supply.objects.filter(
            card=card,
            supply_date__month=today.month,
            supply_date__year=today.year,
        ).aggregate(amount_expensed=Sum('amount'))

    return {"card": card, "supplies": supplies_for_card, "consumption": consumption_card['amount_expensed']}


def print_as_pdf(request, pk):
    response = HttpResponse(content_type="application/pdf")
    response['Content-Disposition'] = f"inline; attachment; filename=approv-{tz.now()}.pdf"
    response["Content-Transfer-Encoding"] = 'binary'

    data = get_data(pk=pk)
    html_string = render_to_string("carburant/pdf-output.html",
                                   context={
                                       "total": data['consumption'],
                                       "card": data['card'],
                                       "supplies": data['supplies'],
                                   }
                               )

    html = HTML(string=html_string)
    result = html.write_pdf()

    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output_file = open(output.name, 'rb')
        response.write(output_file.read())

    return response


def convert_to_csv(request, pk):
    supplies = Supply.objects.filter(
        card=pk,
        supply_date__month=today.month,
        supply_date__year=today.year,
    ) #.values()
    data = get_data(pk=pk)

    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = f"attachment;\
        filename='carte-{ data['card'] }-{ today.month-1 }-{ today.year }.csv'"
    response['Content-Transfer-Encoding'] = "binary"

    writer = csv.writer(response)
    writer.writerow(
        ["CARTE", "DATE APPROV.", "TICKET", "QUANTITE", 'MONTANT', 'VEHICULE', 'SERVICE', 'OBSERVATION', "SIGNATURE"])
    # writer.writerow(["2", "Meco", "Deboue", 28, "France"])

    for supply in supplies:
        writer.writerow([supply.card, supply.supply_date, supply.ticket, supply.volume, supply.amount,
                        supply.vehicle, supply.service, supply.observation, supply.signature])

    # AFFICHAGE DES STATISTIQUES
    writer.writerow([""])
    writer.writerow([""])
    writer.writerow([""])
    writer.writerow(["", "DOTATION", "", data['card'].initial_amount])
    writer.writerow(["", "CONSOMMATION", "", data['consumption_card']['amount_expensed']])
    writer.writerow(["", "RESTE", "", data['card'].balance])

    return response

carburant/templates/carburant/card_form.html
{% extends 'master.html' %}
{% block title %}Ajouter un nouveau véhicule{% endblock title %}

{% block content %}
    <div class="cell-md-4 offset-md-4 cell-sm-12 ">
        <div class="text-center">
            <div class="card bd-teal">
                <form action="" method="post">
                    <div class="card-header text-bold text-center text-leader text-upper bg-grayBlue fg-white">
                        Enregistrer une nouvelle carte
                    </div>
                    <div class="card-content px-5 py-2">
                        {% csrf_token %}
                        {% include 'includes/form.html' %}
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="button bg-grayBlue px-10 fg-white" value="Valider">
                        <input type="reset" class="button bg-dark px-10 fg-white" value="Annuler">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

carburant/templates/carburant/cards.html
{% extends 'master.html' %}
{% block title %}Liste des cartes carburant{% endblock title %}
{% load humanize carburant_tags %}

{% block content %}
    <div class="cell-lg-10 offset-lg-1">
        {% card_list %}
    </div>
{% endblock content %}

carburant/templates/carburant/form.html
{% extends 'master.html' %}
{% block title %}Ajouter un approvisionnement{% endblock %}
{% load widget_tweaks %}

{% block content %}
    <div class="row mt-10-minus">
        <div class="cell-lg-6 offset-lg-3 cell-md-6 offset-md-3">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                <div class="card bg-lightGray simple-shadow">
                    <div class="card-header text-upper text-center bg-darkRed fg-white">
                        Ajouter un nouvel approvisionnement
                    </div>
                    <div class="card-content">
                        <div class="fg-red">{% render_field form.errors %}</div>
                        <div class="container">
                            <div class="row">
                                <div class="cell-lg-12">
                                    <label>Date</label>
                                    {% render_field form.supply_date data-role="calendarpicker" tabindex="1"  %}
                                </div>
                                <div class="cell-12">
                                    <div class="row">
                                        <div class="cell-lg-6">
                                            <label>Ticket</label>
                                            {% render_field form.ticket data-role="spinner" tabindex="2" %}
                                        </div>
                                        <div class="cell-lg-6">
                                            <label for="qte">Quantité (L)</label>
                                            {% render_field form.volume tabindex="3" %}
                                        </div>
                                    </div>
                                </div>
                                <div class="cell-12">
                                    <div class="row">
                                        <div class="cell-lg-6">
                                            <label for="montant">Montant (Fcfa)</label>
                                            {% render_field form.amount data-role="spinner" tabindex="4" %}
                                        </div>
                                        <div class="cell-lg-6">
                                            <label for="km">Km</label>
                                            {% render_field form.odometer data-role="spinner" tabindex="5" %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="cell-12">
                                    <label for="sce">Service</label>
                                    {% render_field form.service tabindex="6" %}
                                </div>
                                <div class="cell-12">
                                    <label for="sign">Signature</label>
                                    {% render_field form.signature tabindex="7" %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="cell-6">
                                    <label for="car">Véhicule</label>
                                    {% render_field form.vehicle tabindex="9" %}
                                </div>
                                <div class="cell-6">
                                    <label for="card">No carte</label>
                                    {% render_field form.card tabindex="10" data-role="select" %}
                                </div>
                            </div>
                            <div class="row">
                                <div class="cell-12 ">
                                    <label for="obs">Observations</label>
                                    {% render_field form.observation data-role="textarea" data-auto-size="false" rows="4" tabindex="11" %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="button alert outline ml-1 w-100" tabindex="12">Enregistrer</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

carburant/templates/carburant/index.html
{% extends 'master.html' %}
{% block title %}Tableau de bord{% endblock title %}
{% load humanize carburant_tags %}

{% block content %}
    <div class="cell-lg-10 offset-lg-1">
        <div class="row border-bottom bd-teal border-5 py-5 my-3 bg-grayBlue">
            <div class="container cell-md-12">
                <div class="text-center">
                <a class="mr-5" href="{% url 'new_card' %}">
                    <button class="image-button bg-darkRed-hover fg-white-hover">
                        <span class="mif-discover credit-card icon"></span>
                        <span class="caption text-upper">Nouvelle carte</span>
                    </button>
                </a>
                <a class="mr-5" href="{% url 'new_vehicle' %}">
                    <button class="image-button  bg-darkRed-hover fg-white-hover">
                        <span class="mif-bus icon"></span>
                        <span class="caption text-upper">Nouveau véhicule</span>
                    </button>
                </a>
                <a class="" href="{% url 'create_supply' %}">
                    <button class="image-button bg-darkRed-hover fg-white-hover">
                        <span class="mif-gas-station icon"></span>
                        <span class="caption text-upper">Nouvel Approvisionnement</span>
                    </button>
                </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="cell-md-4">
                <div class="more-info-box bg-red fg-white">
                    <div class="content">
                        <h2 class="mb-0 text-bold">
                            {% if supplies_count < 10 %}
                                0{{ supplies_count }}
                            {% else %}
                                {{ supplies_count }}
                            {% endif %}
                        </h2>
                        <div class="text-upper">Approvisionnements</div>
                    </div>
                    <div class="icon">
                        <span class="mif-gas-station"></span>
                    </div>
                    <a href="{% url 'supplies' %}" class="more">Voir les approvisionnements <span class="mif-arrow-right"></span></a>
                </div>
            </div>

            <div class="cell-md-4">
                <div class="more-info-box bg-red fg-white">
                    <div class="content">
                        <h2 class="mb-0 text-bold">
                            {% if cards_count < 10 %}
                                0{{ cards_count }}
                            {% else %}
                                {{ cards_count }}
                            {% endif %}
                        </h2>
                        <div class="text-upper">Cartes</div>
                    </div>
                    <div class="icon">
                        <span class="mif-credit-card"></span>
                    </div>
                    <a href="{% url 'cards' %}" class="more">Voir toutes les cartes <span class="mif-arrow-right"></span></a>
                </div>
            </div>

            <div class="cell-md-4">
                <div class="more-info-box bg-red fg-white">
                    <div class="content">
                        <h2 class="mb-0 text-bold ">
                            {% if vehicles_count < 10 %}
                                0{{ vehicles_count }}
                            {% else %}
                                {{ vehicles_count }}
                            {% endif %}
                        </h2>
                        <div class="text-upper">Véhicules</div>
                    </div>
                    <div class="icon">
                        <span class="mif-truck"></span>
                    </div>
                    <a href="{% url 'vehicles' %}" class="more">Voir tous les véhicules de service <span class="mif-arrow-right"></span></a>
                </div>
            </div>
        </div>
        <hr class="border-bottom border-5 bd-teal my-2">
        <div class="row">
            <div class="cell-lg-8">
                <div class="card">
                    <div class="card-header text-leader bg-teal text-upper fg-white text-bold">
                        Liste des véhicles de service
                    </div>
                    <div class="card-content py-2 px-5">
                        {% vehicle_list %}
                    </div>
                </div>
            </div>
            <div class="cell-lg-4">
                <div class="card">
                    <div class="card-header text-leader bg-teal text-upper fg-white text-bold">
                        Liste des cartes de carburants
                    </div>
                    <div class="card-content py-2 px-5">
                        {% card_dashboard_list %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

carburant/templates/carburant/pdf-output.html
{% extends 'master.html' %}
{% load humanize carburant_tags %}
{% block title %}Carte No {{ card.card_number }}{% endblock title %}
{% block navbar %}{% endblock %}

{% block content %}

    <div class="cell-lg-12">
        <div class="">
            <div class="panel">
                <div class="panel-title text-leader d-flex flex-justify-center text-upper text-bold bg-grayBlue fg-white">
                    Carte N° {{ card.card_number }}
                    ({% recharge_period card "%b %Y" %})
{#                    {% for item in card.recharges.all %}#}
{#                        #}
{#                    {% endfor %}#}
                </div>
                <hr>
                <div class="panel-content">
                    <table class="table striped table-border bg-lightGray table-border" style="width: 100%">
                        <thead class="bg fg-white text-upper">
                            <tr>
                                <th>#</th>
                                <th>Carte</th>
                                <th>Date</th>
                                <th>Ticket</th>
                                <th>Qté</th>
                                <th>Montant</th>
                                <th>Véhicule</th>
                                <th>Service</th>
                                <th>Observation</th>
                                <th>Signature</th>
                            </tr>
                        </thead>

                        <tbody style="font-size: 16px; margin-bottom: 30px; color: #0b4059; border-bottom: #0b4059 solid 2px">
                            {% supplies_for_this_month card %}
                        </tbody>
                        <tfoot class="bg-lightTaupe text-upper">
                            <tr>
                                <td colspan="8" class="no-border"></td>
                                <td>Dotation</td>
                                <td class="place-right">{{ card.initial_amount | intcomma }} Fcfa</td>
                            </tr>
                            <tr>
                                <td colspan="8" class="no-border"></td>
                                <td>Conso.</td>
                                <td class="place-right">{{ total | intcomma }} Fcfa</td>
                            </tr>
                            <tr>
                                <td colspan="8" class="no-border"></td>
                                <td>Solde</td>
                                <td class="place-right">{{ card.balance | intcomma }} Fcfa</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <style>
        .panel-title {
            font-size: 20px;
            text-transform: uppercase;
            text-align: center;
            color: #0b4059;
            font-weight: bold;
        }

        thead, tbody {
            background-color: white;
            text-align: center;
        }

        tfoot {
            background-color: #b9d7f5;
            text-transform: uppercase;
            font-weight: bold;
            color: #161515;
        }
        table {
            border-collapse: collapse;
            margin: 20px auto;
        }

        tr:nth-child(even) {
            background-color: #e9ebec;
        }

        th {
            background-color: #0b4059;
            color: white;
        }

        th, td {
            border: #0a1418 solid 1px;
            padding: 2px 3px;
        }

        td.no-border {
            border: none!important;
            background-color: white!important;
        }

        .place-right {
            text-align: right;
        }
    </style>
{% endblock %}