paci/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carburant.urls')),
    path('search', include('search.urls', namespace='search')),
]

search/urls.py
from django.urls import path
from search.views import period_printer

app_name = "search"
urlpatterns = [
    path('', period_printer, name='search'),
]

templates/master.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% block head_meta %}
        <meta charset="UTF-8">
        <meta http-equiv="Content-Language" content="fr-FR">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock head_meta %}
    {% block head_favicon %}
        <link rel="icon" type="image/png" href="{{ STATIC_URL }}images/favicon.png">
    {% endblock head_favicon %}
    {% block cdn_css %}
        <link rel="stylesheet" href="{{ STATIC_URL }}css/metro-all.css">
    {% endblock cdn_css %}
    <style>
        body {
            background-image: url("{{ STATIC_URL }}img/bg6.png");
            background-repeat: repeat-x repeat-y;
            background-attachment: fixed;
        }

        @page {
            size: landscape;
            margin: 2.5cm 1cm 3.5cm 1cm;
{#            background-color: #8b8b8b;#}
            @top-center {
                content: "PRESTIGE AUTO CI";
            }

            table tr {
                border: #0b98da 1px solid;
                background-color: #1a1a1a;
            }
        }
        {% block inner_css %}{% endblock inner_css %}
    </style>
    {% block local_css %}
        <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
    {% endblock local_css %}
    <title>
        {% block title %}Gestion des cartes de carburant{% endblock %}
    </title>
</head>
<body>
    {% block navbar %}
        <nav data-role="appbar" data-expand-point="md" class="bg-darkRed fg-white">
            <a href="{% url 'home' %}" class="brand2 no-hover ml-10 text-leader" style="color: white; text-decoration: none">
                PACI Supply manager
            </a>
            <ul class="app-bar-menu text-upper" style="position: absolute; right: 50px">
                <li><a href="{% url 'cards' %}">Cartes</a></li>
                <li><a href="{% url 'supplies' %}">Approvisionnements</a></li>
                <li><a href="{% url 'vehicles' %}">Véhicules</a></li>
                <li>
                    <a href="" class="dropdown-toggle">Ajouter nouveau</a>
                    <ul class="d-menu" data-role="dropdown">
                        <li><a href="{% url 'create_supply' %}">Approvisionnement</a></li>
                        <li><a href="{% url 'new_card' %}">Carte</a></li>
                        <li><a href="{% url 'new_vehicle' %}">Véhicule</a></li>
                    </ul>
                </li>
    {#            <li><a href="#">Cartes</a></li>#}
            </ul>
        </nav>
    {% endblock navbar %}

    <div class="container mt-20">
        <div class="row">
            {% block content %}{% endblock content %}
        </div>
    </div>

    {% block footer %}{% endblock footer %}
</body>
    {% block cdn_js %}
        <script src="{{ STATIC_URL }}js/metro.js"></script>
    {% endblock %}
</html>

templates/query_form.html
<form action="{% url 'search:search' %}" method="get" class="inline-form flex-justify-center mb-2" style="background-color: #f6e2b4">
    <div class="form-group row flex-justify-center cell-md-8">
        <label for="period" style="line-height: 15px" class="">Choisir une période</label>
        <input type="date" id="period" class="cell-md-3 w-33-md w-100-sm"
               data-role="calendarpicker" name="minDate" value="{{ request.GET.minDate }}">
        <input type="date" class="cell-md-3 w-33-md w-100-sm"
               data-role="calendarpicker" name="maxDate" value="{{ request.GET.maxDate }}">
        {% if card %}
            <input type="hidden" name="card" value="{{ card }}">
        {% endif %}
        <button class="button bg-dark fg-white">Afficher</button>
    </div>
</form>